package Questions;

public class Array {
/* 1: write java program to calculate sum values of an array
 2: WRITE JAVA PROGRAM TO SEARCH SPECIFIC NUMBER IN AN ARRAY
 3:DEFINE AN ARRAY WITH SOME STRING VALUES, WRITE JAVA PROGRAM TO SEARCH 
    SPECIFIC STRING IN AN ARRAY.
4: WRITE A JAVA PROGRAM TO PRINT EVEN AND ODD NUMBER IN AN ARRAY
5: WRITE A PROGRAM TO FIND GREATEST AND SMALLEST ELEMENT IN AN ARRAY
6: WRITE A PROGRAM TO ADD TWO MATRICES */
	
	
	
}
